=== api-evangelist/mindbody/json-schema/public-api-v6-client-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/mindbody/refs/heads/main/json-schema/public-api-v6-client-schema.json",
  "title": "Client",
  "description": "Implementation of the 'Client' model. The Client.",
  "type": "object",
  "properties": {
    "AppointmentGenderPreference": {
      "$ref": "#/components/schemas/AppointmentGenderPreference1Enum",
      "description": "The gender of staff member with whom the client prefers to book appointments."
    },
    "BirthDate": {
      "type": "string",
      "format": "date-time",
      "description": "The client\u2019s date of birth.",
      "example": "2026-05-28T14:30:00Z"
    },
    "Country": {
      "type": "string",
      "description": "The client\u2019s country.",
      "example": "US"
    },
    "CreationDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date the client\u2019s profile was created and added to the business, either by the client from the online store, or by a staff member. This value always returns in the format `yyyy-mm-ddThh:mm:ss:ms`.",
      "example": "2026-05-28T14:30:00Z"
    },
    "CustomClientFields": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/CustomClientFieldValue"
      },
      "description": "Contains information about the custom fields used for clients in the business.",
      "example": [
        {}
      ]
    },
    "ClientCreditCard": {
      "$ref": "#/components/schemas/ClientCreditCard",
      "description": "Contains information about the client\u2019s credit card."
    },
    "ClientIndexes": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/AssignedClientIndex"
      },
      "description": "Contains the IDs of the client\u2019s assigned ClientIndexes and ClientIndexValues. If an index is already assigned to the client, it is overwritten with the passed index value. You cannot currently remove client indexes using the Public API. Only the indexes passed in the request are returned in the response.",
      "example": [
        {}
      ]
    },
    "ClientRelationships": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/ClientRelationship"
      },
      "description": "Contains information about the relationship between two clients. This parameter does not include all of the relationships assigned to the client, only the ones passed in the request.",
      "example": [
        {}
      ]
    },
    "FirstAppointmentDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date of the client\u2019s first booked appointment at the business.",
      "example": "2026-05-28T14:30:00Z"
    },
    "FirstClassDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date of the clients first booked class at the business.",
      "example": "2026-05-28T14:30:00Z"
    },
    "FirstName": {
      "type": "string",
      "description": "The client\u2019s first name.",
      "example": "Alex"
    },
    "Id": {
      "type": "string",
      "description": "The client\u2019s ID, as configured by the business owner. This is the client\u2019s barcode ID if the business owner assigns barcodes to clients. This ID is used throughout the Public API for client-related Public API calls. When used in a POST `UpdateClient` request, the `Id` is used to identify the client for the update.",
      "example": "example-value"
    },
    "IsCompany": {
      "type": "boolean",
      "description": "When `true`, indicates that the client should be marked as a company at the business.<br /> When `false`, indicates the client is an individual and does not represent a company.",
      "example": true
    },
    "IsProspect": {
      "type": "boolean",
      "description": "This value is set only if the business owner allows individuals to be prospects.<br /> When `true`, indicates that the client should be marked as a prospect for the business.<br /> When `false`, indicates that the client should not be marked as a prospect for the business.",
      "example": true
    },
    "LastName": {
      "type": "string",
      "description": "The client\u2019s last name.",
      "example": "Lane"
    },
    "Liability": {
      "$ref": "#/components/schemas/Liability",
      "description": "Contains the client\u2019s liability agreement information for the business."
    },
    "LiabilityRelease": {
      "type": "boolean",
      "description": "Passing `true` sets the client\u2019s liability information as follows: * `IsReleased` is set to `true`. * `AgreementDate` is set to the time zone of the business when the call was processed. * `ReleasedBy` is set to `null` if the call is made by the client, `0` if the call was made by the business owner, or to a specific staff member\u2019s ID if a staff member made the call. Passing `false` sets the client\u2019s liability information as follows: * `IsReleased` is set to `false`. * `AgreementDate` is set to ",
      "example": true
    },
    "MembershipIcon": {
      "type": "integer",
      "format": "int32",
      "description": "The ID of the [membership icon](https://support.mindbodyonline.com/s/article/203259703-Member ship-Setup-screen?language=en_US) displayed next to the client\u2019s name, if the client has a membership on their account.",
      "example": 1
    },
    "MobileProvider": {
      "type": "integer",
      "format": "int32",
      "description": "The client\u2019s mobile provider.",
      "example": 1
    },
    "Notes": {
      "type": "string",
      "description": "Any notes entered on the client\u2019s account by staff members. This value should never be shown to clients unless the business owner has a specific reason for showing them.",
      "example": "Example note for Mindbody Public API."
    },
    "State": {
      "type": "string",
      "description": "The client\u2019s state.",
      "example": "CA"
    },
    "UniqueId": {
      "type": "integer",
      "format": "int32",
      "description": "The client\u2019s system-generated ID at the business. This value cannot be changed by business owners and is always unique across all clients at the business. This ID is not widely used in the Public API, but can be used by your application to uniquely identify clients.",
      "example": 123456
    },
    "LastModifiedDateTime": {
      "type": "string",
      "format": "date-time",
      "description": "The UTC date and time when the client\u2019s information was last modified.",
      "example": "2026-05-28T14:30:00Z"
    },
    "RedAlert": {
      "type": "string",
      "description": "Contains any red alert information entered by the business owner for the client.",
      "example": "example-value"
    },
    "YellowAlert": {
      "type": "string",
      "description": "Contains any yellow alert information entered by the business owner for the client.",
      "example": "example-value"
    },
    "MiddleName": {
      "type": "string",
      "description": "The client\u2019s middle name.",
      "example": "example-value"
    },
    "ProspectStage": {
      "$ref": "#/components/schemas/ProspectStage",
      "description": "Contains information about the client [prospect stage](https://support.mindbodyonline.com/s/article/206176457-Prosp ect-Stages?language=en_US)."
    },
    "Email": {
      "type": "string",
      "description": "The client\u2019s email address.",
      "example": "kinlane@example.com"
    },
    "MobilePhone": {
      "type": "string",
      "description": "The client\u2019s mobile phone number.",
      "example": "+15551234567"
    },
    "HomePhone": {
      "type": "string",
      "description": "The client\u2019s home phone number.",
      "example": "+15551234567"
    },
    "WorkPhone": {
      "type": "string",
      "description": "The client\u2019s work phone number.",
      "example": "+15551234567"
    },
    "AccountBalance": {
      "type": "number",
      "format": "double",
      "description": "The client\u2019s current [account balance](https://mindbody-online-support.force.com/support/s/articl e/203262013-Adding-account-payments-video-tutorial?language=en_US).",
      "example": 49.99
    },
    "AddressLine1": {
      "type": "string",
      "description": "The first line of the client\u2019s street address.",
      "example": "123 Market St"
    },
    "AddressLine2": {
      "type": "string",
      "description": "The second line of the client\u2019s street address, if needed.",
      "example": "123 Market St"
    },
    "City": {
      "type": "string",
      "description": "The client\u2019s city.",
      "example": "San Francisco"
    },
    "PostalCode": {
      "type": "string",
      "description": "The client\u2019s postal code.",
      "example": "94110"
    },
    "WorkExtension": {
      "type": "string",
      "description": "The client\u2019s work phone extension number.",
      "example": "example-value"
    },
    "ReferredBy": {
      "type": "string",
      "description": "Specifies how the client was referred to the business. You can get a list of possible strings using the `GetClientReferralTypes` endpoint.",
      "example": "example-value"
    },
    "PhotoUrl": {
      "type": "string",
      "description": "The URL of the client\u2019s photo for the client profile.",
      "example": "https://example.mindbodyonline.com/resource/abc123"
    },
    "EmergencyContactInfoName": {
      "type": "string",
      "description": "The name of the client\u2019s emergency contact.",
      "example": "example-value"
    },
    "EmergencyContactInfoEmail": {
      "type": "string",
      "description": "The email address of the client\u2019s emergency contact.",
      "example": "kinlane@example.com"
    },
    "EmergencyContactInfoPhone": {
      "type": "string",
      "description": "The phone number of the client\u2019s emergency contact.",
      "example": "+15551234567"
    },
    "EmergencyContactInfoRelationship": {
      "type": "string",
      "description": "The client\u2019s relationship with the emergency contact.",
      "example": "example-value"
    },
    "Gender": {
      "type": "string",
      "description": "The gender of the client.",
      "example": "example-value"
    },
    "LastFormulaNotes": {
      "type": "string",
      "description": "The last [formula note](https://support.mindbodyonline.com/s/article/203259903-Appoin tments-Formula-notes?language=en_US) entered for the client.",
      "example": "Example note for Mindbody Public API."
    },
    "Active": {
      "type": "boolean",
      "description": "When `true`, indicates that the client\u2019s profile is marked as active on the site.<br /> When `false`, the client\u2019s profile is inactive. Defaults to `true` based on the assumption that if a client is currently inactive OR is to be marked inactive, this property will explicitly be mapped/set to `false`.",
      "example": true
    },
    "SalesReps": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/SalesRep"
      },
      "description": "A list of sales representatives.",
      "example": [
        {}
      ]
    },
    "Status": {
      "type": "string",
      "description": "The status of the client in the business. Possible values are: * Declined * Non-Member * Active * Expired * Suspended * Terminated",
      "example": "Active"
    },
    "Action": {
      "$ref": "#/components/schemas/Action1Enum",
      "description": "The action taken."
    },
    "SendAccountEmails": {
      "type": "boolean",
      "description": "When `true`, indicates that the client has opted to receive general account notifications by email. This property is editable. <br />Default: **false**",
      "example": true
    },
    "SendAccountTexts": {
      "type": "boolean",
      "description": "When `true`, indicates that the client has opted to receive general account notifications by text message. This parameter cannot be updated by developers. If included in a request, it is ignored.",
      "example": true
    },
    "SendPromotionalEmails": {
      "type": "boolean",
      "description": "When `true`, indicates that the client has opted to receive promotional notifications by email. This property is editable. <br />Default: **false**",
      "example": true
    },
    "SendPromotionalTexts": {
      "type": "boolean",
      "description": "When `true`, indicates that the client has opted to receive promotional notifications by text message. This parameter cannot be updated by developers. If included in a request, it is ignored.",
      "example": true
    },
    "SendScheduleEmails": {
      "type": "boolean",
      "description": "When `true`, indicates that the client has opted to receive schedule notifications by email. This property is editable. <br />Default: **false**",
      "example": true
    },
    "SendScheduleTexts": {
      "type": "boolean",
      "description": "When `true`, indicates that the client has opted to receive schedule notifications by text message. This parameter cannot be updated by developers. If included in a request, it is ignored.",
      "example": true
    },
    "HomeLocation": {
      "$ref": "#/components/schemas/Location",
      "description": "Information about the Home Location for this client"
    },
    "LockerNumber": {
      "type": "string",
      "description": "The clients locker number.",
      "example": "example-value"
    },
    "ClientType": {
      "$ref": "#/components/schemas/ClientType",
      "description": "The client's assigned client type. Returns null if the client has no client type assigned. For more information, see [Client Types](https://support.mindbodyonline.com/s/article/203259193-Clien t-Types)."
    }
  }
}

=== api-evangelist/mindbody/examples/public-api-v6-client-example.json
{
  "AppointmentGenderPreference": "None",
  "BirthDate": "2026-05-28T14:30:00Z",
  "Country": "US",
  "CreationDate": "2026-05-28T14:30:00Z",
  "CustomClientFields": [
    {}
  ],
  "ClientCreditCard": {
    "Address": "123 Market St",
    "CardHolder": "example-value",
    "CardNumber": "example-value",
    "CardType": "example-value",
    "City": "San Francisco",
    "ExpMonth": "example-value",
    "ExpYear": "example-value",
    "LastFour": "example-value",
    "PostalCode": "94110",
    "State": "CA"
  },
  "ClientIndexes": [
    {}
  ],
  "ClientRelationships": [
    {}
  ],
  "FirstAppointmentDate": "2026-05-28T14:30:00Z",
  "FirstClassDate": "2026-05-28T14:30:00Z",
  "FirstName": "Alex",
  "Id": "example-value",
  "IsCompany": true,
  "IsProspect": true,
  "LastName": "Lane",
  "Liability": {
    "AgreementDate": "2026-05-28T14:30:00Z",
    "IsReleased": true,
    "ReleasedBy": 1
  },
  "LiabilityRelease": true,
  "MembershipIcon": 1,
  "MobileProvider": 1,
  "Notes": "Example note for Mindbody Public API.",
  "State": "CA",
  "UniqueId": 123456,
  "LastModifiedDateTime": "2026-05-28T14:30:00Z",
  "RedAlert": "example-value",
  "YellowAlert": "example-value",
  "MiddleName": "example-value",
  "ProspectStage": {
    "Active": true,
    "Description": "Example note for Mindbody Public API.",
    "Id": 123456
  },
  "Email": "kinlane@example.com",
  "MobilePhone": "+15551234567",
  "HomePhone": "+15551234567",
  "WorkPhone": "+15551234567",
  "AccountBalance": 49.99,
  "AddressLine1": "123 Market St",
  "AddressLine2": "123 Market St",
  "City": "San Francisco",
  "PostalCode": "94110",
  "WorkExtension": "example-value",
  "ReferredBy": "example-value",
  "PhotoUrl": "https://example.mindbodyonline.com/resource/abc123",
  "EmergencyContactInfoName": "example-value",
  "EmergencyContactInfoEmail": "kinlane@example.com",
  "EmergencyContactInfoPhone": "+15551234567",
  "EmergencyContactInfoRelationship": "example-value",
  "Gender": "example-value",
  "LastFormulaNotes": "Example note for Mindbody Public API.",
  "Active": true,
  "SalesReps": [
    {}
  ],
  "Status": "Active",
  "Action": "None",
  "SendAccountEmails": true,
  "SendAccountTexts": true,
  "SendPromotionalEmails": true,
  "SendPromotionalTexts": true,
  "SendScheduleEmails": true,
  "SendScheduleTexts": true,
  "HomeLocation": {
    "AdditionalImageURLs": [
      "example-value"
    ],
    "Address": "123 Market St",
    "Address2": "123 Market St",
    "Amenities": [
      {}
    ],
    "BusinessDescription": "Example note for Mindbody Public API.",
    "City": "San Francisco",
    "Description": "Example note for Mindbody Public API.",
    "HasClasses": true,
    "Id": 123456,
    "Latitude": 1.0,
    "Longitude": 1.0,
    "Name": "Sunset Yoga Studio",
    "Phone": "+15551234567",
    "PhoneExtension": "example-value",
    "PostalCode": "94110",
    "SiteID": 1,
    "StateProvCode": "example-value",
    "Tax1": 1.0,
    "Tax2": 1.0,
    "Tax3": 1.0,
    "Tax4": 1.0,
    "Tax5": 1.0,
    "TotalNumberOfRatings": 1,
    "AverageRating": 1.0,
    "TotalNumberOfDeals": 1
  },
  "LockerNumber": "example-value",
  "ClientType": {
    "Id": 123456,
    "Name": "Sunset Yoga Studio"
  }
}
