=== api-evangelist/mindbody/json-schema/public-api-v6-session-type1-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/mindbody/refs/heads/main/json-schema/public-api-v6-session-type1-schema.json",
  "title": "SessionType1",
  "description": "Implementation of the 'SessionType1' model.",
  "type": "object",
  "properties": {
    "Type": {
      "$ref": "#/components/schemas/Type1Enum",
      "description": "The model property of type Type1Enum."
    },
    "DefaultTimeLength": {
      "type": "integer",
      "format": "int32",
      "description": "The model property of type int.",
      "example": 1
    },
    "StaffTimeLength": {
      "type": "integer",
      "format": "int32",
      "description": "The model property of type int.",
      "example": 1
    },
    "ProgramId": {
      "type": "integer",
      "format": "int32",
      "description": "The model property of type int.",
      "example": 123456
    },
    "NumDeducted": {
      "type": "integer",
      "format": "int32",
      "description": "The model property of type int.",
      "example": 1
    },
    "Id": {
      "type": "integer",
      "format": "int32",
      "description": "The model property of type int.",
      "example": 123456
    },
    "Name": {
      "type": "string",
      "description": "The model property of type str.",
      "example": "Sunset Yoga Studio"
    },
    "Active": {
      "type": "boolean",
      "description": "The model property of type bool.",
      "example": true
    },
    "Capacity": {
      "type": "integer",
      "format": "int32",
      "description": "The model property of type int.",
      "example": 1
    },
    "ResourceRequired": {
      "type": "boolean",
      "description": "The model property of type bool.",
      "example": true
    },
    "Category": {
      "$ref": "#/components/schemas/ServiceTag",
      "description": "The model property of type ServiceTag."
    },
    "Subcategory": {
      "$ref": "#/components/schemas/ServiceTag",
      "description": "The model property of type ServiceTag."
    },
    "OnlineDescription": {
      "type": "string",
      "description": "The model property of type str.",
      "example": "Example note for Mindbody Public API."
    },
    "AvailableForAddOn": {
      "type": "boolean",
      "description": "The model property of type bool.",
      "example": true
    }
  }
}

=== api-evangelist/mindbody/examples/public-api-v6-session-type1-example.json
{
  "Type": "All",
  "DefaultTimeLength": 1,
  "StaffTimeLength": 1,
  "ProgramId": 123456,
  "NumDeducted": 1,
  "Id": 123456,
  "Name": "Sunset Yoga Studio",
  "Active": true,
  "Capacity": 1,
  "ResourceRequired": true,
  "Category": {
    "Id": 123456,
    "Name": "Sunset Yoga Studio"
  },
  "Subcategory": {
    "Id": 123456,
    "Name": "Sunset Yoga Studio"
  },
  "OnlineDescription": "Example note for Mindbody Public API.",
  "AvailableForAddOn": true
}
