=== api-evangelist/mindbody/json-schema/public-api-v6-add-promo-code-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/mindbody/refs/heads/main/json-schema/public-api-v6-add-promo-code-request-schema.json",
  "title": "AddPromoCodeRequest",
  "description": "Implementation of the 'AddPromoCodeRequest' model.",
  "type": "object",
  "properties": {
    "Code": {
      "type": "string",
      "description": "The code of the promocode.",
      "example": "example-value"
    },
    "Name": {
      "type": "string",
      "description": "The name of the promocode.",
      "example": "Sunset Yoga Studio"
    },
    "Active": {
      "type": "boolean",
      "description": "Indicates that promocode is active. Default: **true**",
      "example": true
    },
    "Discount": {
      "$ref": "#/components/schemas/Discount",
      "description": "Discount info"
    },
    "ActivationDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date of the promocode activation. Default: **today\u2019s date**",
      "example": "2026-05-28T14:30:00Z"
    },
    "ExpirationDate": {
      "type": "string",
      "format": "date-time",
      "description": "The date of the promocode expiration. Default: **a months from today\u2019s date**",
      "example": "2026-05-28T14:30:00Z"
    },
    "MaxUses": {
      "type": "integer",
      "format": "int32",
      "description": "The maximun number of uses. A use is considered a single sale.",
      "example": 1
    },
    "DaysAfterCloseDate": {
      "type": "integer",
      "format": "int32",
      "description": "The number of days a client has to use a promocode after they are no longer a prospect.",
      "example": 1
    },
    "AllowOnline": {
      "type": "boolean",
      "description": "Indicates if promocode can be redeemed online in consumer mode. Default: **false**",
      "example": true
    },
    "DaysValid": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Indicates what days of the week promocode is valid. Defaults to 7 days of the week. Possible values are: * Monday * Tuesday * Wednesday * Thursday * Friday * Saturday * Sunday",
      "example": [
        "example-value"
      ]
    },
    "ApplicableItems": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/ApplicableItem"
      },
      "description": "Contains information about a promocode applicable items. See ApplicableItems for a details of the `ApplicableItems` object.",
      "example": [
        {}
      ]
    }
  }
}

=== api-evangelist/mindbody/examples/public-api-v6-add-promo-code-request-example.json
{
  "Code": "example-value",
  "Name": "Sunset Yoga Studio",
  "Active": true,
  "Discount": {
    "Type": "example-value",
    "Amount": 49.99
  },
  "ActivationDate": "2026-05-28T14:30:00Z",
  "ExpirationDate": "2026-05-28T14:30:00Z",
  "MaxUses": 1,
  "DaysAfterCloseDate": 1,
  "AllowOnline": true,
  "DaysValid": [
    "example-value"
  ],
  "ApplicableItems": [
    {}
  ]
}
